export const photosFeed = [
  {
    id: 1,
    url: "/photos/engagement_1.jpg",
    alt: "Engagement Photo 1",
    likes: "93901750",
    comments: "88586857",
    caption:
      "They said YES to each other! I already said yes to both of them years ago, so this was really just a formality. 💍 - Oz",
    timestamp: "8 months ago",
  },
  {
    id: 2,
    url: "/photos/engagement_2.jpg",
    alt: "Engagement Photo 2",
    likes: "93901750",
    comments: "88586857",
    caption: "More engagement photos. Still no one asking ME if I want to get engaged. Rude. - Oz",
    timestamp: "8 months ago",
  },
  {
    id: 3,
    url: "/photos/engagement_dinner.jpeg",
    alt: "Engagement Dinner",
    likes: "93901750",
    comments: "88586857",
    caption: "Engagement dinner! I wasn't invited but I heard there were appetizers. This is what I'm dealing with here. - Oz",
    timestamp: "8 months ago",
  },
  {
    id: 4,
    url: "/photos/north_hike_with_oz.JPG",
    alt: "Hiking with Oz",
    likes: "93901750",
    comments: "88586857",
    caption: "FINALLY a photo that actually includes me. Best hike of their lives, obviously. I was there. - Oz",
    timestamp: "7 months ago",
  },
  {
    id: 5,
    url: "/photos/oz_felt_cute.jpeg",
    alt: "Oz Feeling Cute",
    likes: "99999999",
    comments: "99999999",
    caption: "Felt cute, might delete later. (Just kidding, I look incredible and this is staying up forever) - Oz",
    timestamp: "6 months ago",
  },
  {
    id: 6,
    url: "/photos/boat_trip.jpeg",
    alt: "Boat Trip",
    likes: "93901750",
    comments: "88586857",
    caption: "Boat day! The humans got seasick. I did not. Superior species confirmed. - Oz",
    timestamp: "6 months ago",
  },
  {
    id: 7,
    url: "/photos/ceramics_lesson.png",
    alt: "Ceramics Lesson",
    likes: "93901750",
    comments: "88586857",
    caption: "They took a ceramics class. I could have made better bowls with my paws but sure, go off. - Oz",
    timestamp: "6 months ago",
  },
  {
    id: 8,
    url: "/photos/france_village.jpeg",
    alt: "French Village",
    likes: "93901750",
    comments: "88586857",
    caption: "France! Land of cheese, wine, and me being left at home with a petsitter. Zero stars. - Oz",
    timestamp: "5 months ago",
  },
  {
    id: 9,
    url: "/photos/france_dinner.jpeg",
    alt: "France Dinner",
    likes: "93901750",
    comments: "88586857",
    caption: "Look at them eating fancy French food while I'm stuck with kibble. I'm calling my lawyer. - Oz",
    timestamp: "5 months ago",
  },
  {
    id: 10,
    url: "/photos/lavendar_fields.jpeg",
    alt: "Lavender Fields",
    likes: "93901750",
    comments: "88586857",
    caption: "Lavender fields in France. Probably smells nice. I wouldn't know. I WAS AT HOME. - Oz",
    timestamp: "5 months ago",
  },
  {
    id: 11,
    url: "/photos/portugal.jpeg",
    alt: "Portugal",
    likes: "93901750",
    comments: "88586857",
    caption: "Portugal! Another trip without me. Starting to think they don't understand I'm the best travel companion. - Oz",
    timestamp: "5 months ago",
  },
  {
    id: 12,
    url: "/photos/jamaica_hammock.JPG",
    alt: "Jamaica Hammock",
    likes: "93901750",
    comments: "88586857",
    caption: "Jamaica hammock vibes. I bet I'd look great in a hammock. We'll never know because SOME DOGS weren't invited. - Oz",
    timestamp: "4 months ago",
  },
  {
    id: 13,
    url: "/photos/jamaica_sunset.jpeg",
    alt: "Jamaica Sunset",
    likes: "93901750",
    comments: "88586857",
    caption: "Jamaica sunset. Beautiful. Tragic. I'm experiencing complex emotions about not being there. - Oz",
    timestamp: "4 months ago",
  },
  {
    id: 14,
    url: "/photos/thailand_temple.JPG",
    alt: "Thailand Temple",
    likes: "93901750",
    comments: "88586857",
    caption: "Thailand temple. Very spiritual. I'm spiritual too. I meditate every time they leave the house (on the couch). - Oz",
    timestamp: "4 months ago",
  },
  {
    id: 15,
    url: "/photos/thailand_hike.JPG",
    alt: "Thailand Hike",
    likes: "93901750",
    comments: "88586857",
    caption: "Hiking in Thailand without their BEST HIKING BUDDY. Remember the photo from earlier where I was on a hike? Yeah. - Oz",
    timestamp: "4 months ago",
  },
  {
    id: 16,
    url: "/photos/prague_cold_weather.jpeg",
    alt: "Prague Cold Weather",
    likes: "93901750",
    comments: "88586857",
    caption: "Prague in the cold. I have a fur coat. I was MADE for this weather. But sure, leave me behind. - Oz",
    timestamp: "3 months ago",
  },
  {
    id: 17,
    url: "/photos/new_york.jpeg",
    alt: "New York",
    likes: "93901750",
    comments: "88586857",
    caption: "New York City! The Big Apple! I've heard dogs love it there. This is just speculation on my part. - Oz",
    timestamp: "3 months ago",
  },
  {
    id: 18,
    url: "/photos/new_york_2.jpeg",
    alt: "New York 2",
    likes: "93901750",
    comments: "88586857",
    caption: "More NYC content. Living their best lives. Meanwhile I'm living my DECENT life. It's fine. I'm fine. - Oz",
    timestamp: "3 months ago",
  },
  {
    id: 19,
    url: "/photos/jerusalem_hills.jpeg",
    alt: "Jerusalem Hills",
    likes: "93901750",
    comments: "88586857",
    caption: "Jerusalem hills. Historic. Beautiful. Would have been better with a dog in the frame. Just saying. - Oz",
    timestamp: "3 months ago",
  },
  {
    id: 20,
    url: "/photos/park-hamesila.jpg",
    alt: "Park HaMesila",
    likes: "93901750",
    comments: "88586857",
    caption: "Park HaMesila! THIS IS A DOG PARK. I WAS THERE. Finally, some respect. - Oz",
    timestamp: "2 months ago",
  },
  {
    id: 21,
    url: "/photos/sea_hike.jpeg",
    alt: "Sea Hike",
    likes: "93901750",
    comments: "88586857",
    caption: "Hiking by the sea! Water, trails, probably some good sniffs. I should write a travel blog. - Oz",
    timestamp: "2 months ago",
  },
  {
    id: 22,
    url: "/photos/hike_in_usa.jpeg",
    alt: "USA Hike",
    likes: "93901750",
    comments: "88586857",
    caption: "USA hiking vibes. Americans love dogs. I would have been SO popular there. Missed opportunity. - Oz",
    timestamp: "2 months ago",
  },
  {
    id: 23,
    url: "/photos/jacks_apartment_balcony.jpeg",
    alt: "Jack's Apartment Balcony",
    likes: "93901750",
    comments: "88586857",
    caption: "Jack's balcony. I sun myself here. It's my office. I do important work here (napping). - Oz",
    timestamp: "2 months ago",
  },
  {
    id: 24,
    url: "/photos/london_jacks_house.JPG",
    alt: "London - Jack's House",
    likes: "93901750",
    comments: "88586857",
    caption: "London! This is where Jack lived before he met Alex. I wasn't born yet. Dark times for everyone. - Oz",
    timestamp: "15 years ago",
  },
  {
    id: 25,
    url: "/photos/tower_of_london.jpeg",
    alt: "Tower of London",
    likes: "93901750",
    comments: "88586857",
    caption: "Tower of London. Historic. Medieval. They had dogs back then too. Those dogs would get it. - Oz",
    timestamp: "1 month ago",
  },
  {
    id: 26,
    url: "/photos/jack_baby.jpeg",
    alt: "Baby Jack",
    likes: "93901750",
    comments: "88586857",
    caption: "Baby Jack! Before he knew the joy of dog ownership. Look at him, he had no idea what was missing. - Oz",
    timestamp: "30 years ago",
  },
  {
    id: 27,
    url: "/photos/jack_young_balloons.jpeg",
    alt: "Young Jack with Balloons",
    likes: "93901750",
    comments: "88586857",
    caption: "Young Jack with balloons. Cute kid. Would have been cuter with a puppy. Just objectively true. - Oz",
    timestamp: "28 years ago",
  },
  {
    id: 28,
    url: "/photos/jack_cat_costume.jpeg",
    alt: "Jack in Cat Costume",
    likes: "93901750",
    comments: "88586857",
    caption: "Jack dressed as a CAT. We don't talk about this. This is a dark chapter we've all moved past. - Oz",
    timestamp: "27 years ago",
  },
  {
    id: 29,
    url: "/photos/jack_teletubbies_costume.jpeg",
    alt: "Jack in Teletubbies Costume",
    likes: "93901750",
    comments: "88586857",
    caption: "Jack as a Teletubby. I respect the commitment to the bit but PLEASE delete this. - Oz",
    timestamp: "26 years ago",
  },
  {
    id: 30,
    url: "/photos/jack_with_sister_ilana_young_1.jpeg",
    alt: "Young Jack with Sister Ilana",
    likes: "93901750",
    comments: "88586857",
    caption: "Jack with his big sister Ilana! She seems cool. I bet she'd let me on the couch. - Oz",
    timestamp: "27 years ago",
  },
  {
    id: 31,
    url: "/photos/jack_with_sister_ilana_young_2.jpeg",
    alt: "Young Jack with Sister Ilana 2",
    likes: "93901750",
    comments: "88586857",
    caption: "More Jack and Ilana content. Sibling goals. I'm an only dog so I wouldn't know. Living vicariously here. - Oz",
    timestamp: "26 years ago",
  },
  {
    id: 32,
    url: "/photos/jack_parents_wedding.jpeg",
    alt: "Jack's Parents Wedding",
    likes: "93901750",
    comments: "88586857",
    caption: "Jack's parents' wedding! This is where it all started. No dogs in this photo either. The cycle continues. - Oz",
    timestamp: "35 years ago",
  },
  {
    id: 33,
    url: "/photos/alex_young.jpg",
    alt: "Young Alex",
    likes: "93901750",
    comments: "88586857",
    caption: "Baby Alex! Already had that look of someone who would one day give the best ear scratches. - Oz",
    timestamp: "28 years ago",
  },
  {
    id: 34,
    url: "/photos/alex_parents_wedding.JPG",
    alt: "Alex's Parents Wedding",
    likes: "93901750",
    comments: "88586857",
    caption: "Alex's parents' wedding! Beautiful. Classic. Would have been elevated by a ring bearer dog. Missed opportunity. - Oz",
    timestamp: "33 years ago",
  },
  {
    id: 35,
    url: "/photos/devons_wedding.jpg",
    alt: "Devon's Wedding",
    likes: "93901750",
    comments: "88586857",
    caption: "Alex's sister Devon's wedding! Everyone looks so happy. I bet they had a good DJ. Was there a puppy table? - Oz",
    timestamp: "3 years ago",
  },
  {
    id: 36,
    url: "/photos/devon_wedding_bw.jpg",
    alt: "Devon's Wedding B&W",
    likes: "93901750",
    comments: "88586857",
    caption: "Devon's wedding in black & white. Artistic. Timeless. I look good in black & white too. Check photo #5. - Oz",
    timestamp: "3 years ago",
  },
  {
    id: 37,
    url: "/photos/jesse_ariella_wedding.JPG",
    alt: "Jesse & Ariella's Wedding",
    likes: "93901750",
    comments: "88586857",
    caption: "Jesse and Ariella's wedding! Love is in the air. Also pollen. But mostly love. - Oz",
    timestamp: "2 years ago",
  },
];
